### ISSUE TITLE
Implement declaring custom types like 'stuct' or 'class' 

### ISSUE THREAD

**Issue by tejainece** [bonobo-lang/bonobo#4]

**Comment by thosakwe** [comment]
Mixins, etc. will be covered eventually.

```bonobo
{ text: String, completed: Bool, f doIt(): Num }
```

The above is a valid type. However, a typedef (#10) will be more convenient.

**Comment by thosakwe** [comment]
Function declarations in struct types will be required to have type annotations.

**Comment by thosakwe** [comment]
Ref #36 for the current function literal syntax.

**Comment by thosakwe** [comment]
Our current model:

```bonobo
type Point := {
  x: Int
  y: Int
  fn lazy length => x + y
  set name: String {
    ...
  } 
}
```

**Comment by thosakwe** [comment]
I'm wondering how private values might work.

```bonobo
type Access := {
  private name: String
  
  private fn doSomething => ...
}
```

This would require renaming the modifiers `pub` and `priv` to `public` and `private`, which IMO is probably smart.

**Comment by tejainece** [comment]
For the sake of easier parsing:

```
type Access {
  private name: String
  
  fn private doSomething => ...
}
```

**Comment by thosakwe** [comment]
Double colon optional: #46

**Comment by thosakwe** [comment]
```bonobo
type Access {
  hide name: String
  show publicName: String
}
```

**Comment by thosakwe** [comment]
For a struct type, I don't think there should be a notion of visibility, on second thought.

If it turns out that we do need classes, then we will implement visibility.

However, struct/record types won't need them.

Also, closing this, as struct types have now been implemented.
