### ISSUE TITLE
How to group several files into a library

### ISSUE THREAD

**Issue by tejainece** [bonobo-lang/bonobo#5]

**Comment by thosakwe** [comment]
In my head, this is how it goes:

1. All symbols are package-private by default, unless the modifier `pub` is present.

```bonobo
// Public!
pub f one => 1.0

// Package-private
f two => 2.0
```

2. A `package` is a directory that contains Bonobo files. Subdirectories count as sub-packages.

```
foo/
  - a.bnb
  - b.bnb
  - bar/
    - c.bnb
    - d.bnb
    - baz/
      - e.bnb
      - f.bnb 
  - quux/
    - g.bnb
    - h.bnb
```

Defines these packages:
* `foo`: contains `a.bnb, b.bnb`
  * `foo.bar`: contains `c.bnb, d.bnb`
    * `foo.bar.baz`: contains `e.bnb`, `f.bnb`
  * `foo.quux`: contains `g.bnb, h.bnb`

**Comment by thosakwe** [comment]
If you were editing the file `foo/a.bnb`, but you wanted to call a function `doIt()` defined in `foo/bar/d.bnb`, write:

```bonobo
f myFunc => bar.doIt()
```

**Comment by thosakwe** [comment]
In short, you do not need to call `import` for symbols existing in the local tree. I don't plan to allow overriding this. This way, it will be very clear where symbols come from, and also much easier to find their definitions.

**Comment by thosakwe** [comment]
To import third-party libraries: #6

**Comment by tejainece** [comment]
Very intuitive implementation!

**Comment by thosakwe** [comment]
Finally closed. Example: https://github.com/bonobo-lang/bonobo/blob/master/example/modules/main.bnb

Note the `::` namespacing syntax
